# Generated by Django 3.1.1 on 2020-09-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
